# Generated by Django 5.1.4 on 2024-12-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_contactinfo_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='department',
            field=models.CharField(choices=[('sales_department', 'Отдел продаж'), ('support', 'Поддержка')], default='sales_department', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='details',
            field=models.FileField(upload_to='request_files'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
