# Generated by Django 5.1.4 on 2024-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_requestmodel_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='details',
            field=models.FileField(blank=True, null=True, upload_to='call_records'),
        ),
    ]
