# Generated by Django 5.1.4 on 2024-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Возврат одобрен'), ('rejected', 'Возврат отклонен')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('sales_department', 'Отдел продаж'), ('curator', 'Куратор'), ('support', 'Поддержка'), ('refund', 'Возврат')], default='user', max_length=100),
        ),
    ]
