# Generated by Django 5.1.4 on 2024-12-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.user'),
        ),
    ]
